let obj = {
  order: {
    order_id: 665994928,
    order_date: "2026-02-12T22:48:56",
    order_number: "29076",
    reference: "6408949661743",
    carrier: "AusPost",
    carrier_name: "Australia Post",
    carrier_service_code: "3D55",
    signature_required: false,
    dangerous_goods: false,
    currency: "AUD",
    sender_details: {
      name: "Crunch Jar",
      email: "admin@crunchjar.com.au",
      phone: "",
      building: "",
      company: "Crunch Jar",
      street: "PO Box 5621",
      suburb: "Chullora",
      city: "Sydney",
      state: "NSW",
      post_code: "2190",
      country: "Australia",
      tax_numbers: [],
    },
    destination: {
      name: "Adam  Kabbara",
      building: "",
      company: "",
      street: "12 Bromley Avenue",
      suburb: "Greenacre",
      city: "",
      state: "NSW",
      post_code: "2190",
      country: "Australia",
      delivery_instructions: "",
      tax_numbers: [],
    },
    items: [
      {
        item_id: 1744502584,
        description: "Dubai Chocolate Crunch Jar | 350g",
        sku: "SKU350CRUJAR",
        color: "",
        size: "",
        tariff_code: "210690",
        country_of_origin: "Australia",
        quantity: 1,
        quantity_to_ship: 1,
        quantity_shipped: 0,
        weight: 0.4,
        height: 0.0,
        width: 0.0,
        length: 0.0,
        value: 35.0,
        barcode: "9369900087179",
        stock_on_hand: 0,
        return_reason: "",
        additional_return_reason: "",
        returned_items: [],
        brand: "",
        usage: "",
        material: "",
        model: "",
        mid_code: "",
        image_url:
          "https://cdn.shopify.com/s/files/1/0682/5256/5551/files/DSC00918-Enhanced-NR.jpg?v=1755333265",
      },
      {
        item_id: 1744502585,
        description: "Custom 4 PACK",
        sku: "CUSTOM4PACK",
        color: "",
        size: "",
        tariff_code: "",
        country_of_origin: "Australia",
        quantity: 1,
        quantity_to_ship: 1,
        quantity_shipped: 0,
        weight: 1.6,
        height: 0.0,
        width: 0.0,
        length: 0.0,
        value: 99.0,
        barcode: "",
        stock_on_hand: 0,
        return_reason: "",
        additional_return_reason: "",
        returned_items: [],
        brand: "",
        usage: "",
        material: "",
        model: "",
        mid_code: "",
        image_url:
          "https://cdn.shopify.com/s/files/1/0682/5256/5551/files/AUSTRALIA_s_26.png?v=1770888836",
      },
      {
        item_id: 1744502586,
        description: "Strawberries & Cream Crunch Jar",
        sku: "SKUSTRAWBCREAM350",
        color: "",
        size: "",
        tariff_code: "210690",
        country_of_origin: "Australia",
        quantity: 1,
        quantity_to_ship: 1,
        quantity_shipped: 0,
        weight: 0.4,
        height: 0.0,
        width: 0.0,
        length: 0.0,
        value: 30.0,
        barcode: "",
        stock_on_hand: 0,
        return_reason: "",
        additional_return_reason: "",
        returned_items: [],
        brand: "",
        usage: "",
        material: "",
        model: "",
        mid_code: "",
        image_url:
          "https://cdn.shopify.com/s/files/1/0682/5256/5551/files/DSC00728-2.jpg?v=1770887082",
      },
      {
        item_id: 1744502587,
        description: "Biscroff Crunch Jar | 350g",
        sku: "SKUBISCOFF350",
        color: "",
        size: "",
        tariff_code: "210690",
        country_of_origin: "Australia",
        quantity: 4,
        quantity_to_ship: 4,
        quantity_shipped: 0,
        weight: 0.4,
        height: 0.0,
        width: 0.0,
        length: 0.0,
        value: 120.0,
        barcode: "",
        stock_on_hand: 0,
        return_reason: "",
        additional_return_reason: "",
        returned_items: [],
        brand: "",
        usage: "",
        material: "",
        model: "",
        mid_code: "",
        image_url:
          "https://cdn.shopify.com/s/files/1/0682/5256/5551/files/Gemini_Generated_Image_vx7lyqvx7lyqvx7l.png?v=1770851215",
      },
      {
        item_id: 1744502588,
        description: "Bueno Crunch Jar l 350g",
        sku: "SKUBUENO350",
        color: "",
        size: "",
        tariff_code: "210690",
        country_of_origin: "Australia",
        quantity: 1,
        quantity_to_ship: 1,
        quantity_shipped: 0,
        weight: 0.4,
        height: 0.0,
        width: 0.0,
        length: 0.0,
        value: 30.0,
        barcode: "",
        stock_on_hand: 0,
        return_reason: "",
        additional_return_reason: "",
        returned_items: [],
        brand: "",
        usage: "",
        material: "",
        model: "",
        mid_code: "",
        image_url:
          "https://cdn.shopify.com/s/files/1/0682/5256/5551/files/DSC00610-3.jpg?v=1765701325",
      },
      {
        item_id: 1744502589,
        description: "Cookies & Cream Crunch Jar | 350g",
        sku: "SKUCOOKIESCREAM350",
        color: "",
        size: "",
        tariff_code: "210690",
        country_of_origin: "Australia",
        quantity: 1,
        quantity_to_ship: 1,
        quantity_shipped: 0,
        weight: 0.4,
        height: 0.0,
        width: 0.0,
        length: 0.0,
        value: 30.0,
        stock_on_hand: 0,
        return_reason: "",
        additional_return_reason: "",
        returned_items: [],
        brand: "",
        usage: "",
        material: "",
        model: "",
        mid_code: "",
        image_url:
          "https://cdn.shopify.com/s/files/1/0682/5256/5551/files/DSC07931-Enhanced-NR-2.jpg?v=1765421011",
      },
      {
        item_id: 1744502590,
        description: "Biscroff Crunch Jar | 350g",
        sku: "SKUBISCOFF350",
        color: "",
        size: "",
        tariff_code: "210690",
        country_of_origin: "Australia",
        quantity: 1,
        quantity_to_ship: 1,
        quantity_shipped: 0,
        weight: 0.4,
        height: 0.0,
        width: 0.0,
        length: 0.0,
        value: 30.0,
        barcode: "",
        stock_on_hand: 0,
        return_reason: "",
        additional_return_reason: "",
        returned_items: [],
        brand: "",
        usage: "",
        material: "",
        model: "",
        mid_code: "",
        image_url:
          "https://cdn.shopify.com/s/files/1/0682/5256/5551/files/Gemini_Generated_Image_vx7lyqvx7lyqvx7l.png?v=1770851215",
      },
    ],
    packages: [
      {
        package_id: 835247028,
        name: "Default",
        weight: 4.0,
        height: 0.01,
        width: 0.05,
        length: 0.1,
        packaging_type: "Carton",
        carrier_service_code: "3D55",
        carrier_service_name: "PARCEL POST + SIGNATURE",
        tracking_url: "https://auspost.com.au/mypost/track/details/",
        shipment_type: "Outgoing",
      },
    ],
    metadatas: [
      { metafield_key: "ADDRESSVALIDATED", value: "True", required: false },
      { metafield_key: "SOURCE", value: "Shopify", required: false },
      { metafield_key: "ATL", value: "True", required: false },
      { metafield_key: "SAFEDROP", value: "True", required: false },
      { metafield_key: "CREATERETURN", value: "False", required: false },
      { metafield_key: "INSURANCE", value: "False", required: false },
      { metafield_key: "INSURANCEVALUE", value: "0.00", required: false },
      { metafield_key: "DANGEROUSGOODS", value: "False", required: false },
    ],
    declared_value: 734.0,
    archived: false,
    manifest_number: 0,
    writeback_status: "",
    address_validation: "Valid",
    create_return: false,
    dtp: false,
    duties_amount: 0.0,
    tax_amount: 0.0,
    export_type: "",
    add_insurance: false,
    insurance_value: 0.0,
    plt: false,
    type: "Outgoing",
    platform: "Shopify",
    status: "Saved",
    manifested: false,
    price_breakdown: {
      "Calculated Price ex GST": "$6.47",
      "Calculated GST": "$0.65",
      "Calculated Price": "$7.12",
      "Predicted Delivery Dates ": "1-2 days",
    },
    total_shipping_price: 7.12,
    shipping_freight_value: 0.0,
    tags: ["Packing Slip Printed"],
    has_commercial_invoice: false,
    is_fully_packed: false,
  },
  success: true,
};
